# Generated by Django 5.1.6 on 2025-02-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0003_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
